language: groovy

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

script:
  - ./gradlew clean assemble cobertura uploadArchives
  - cd samples/xml && ./gradlew replacerClean replacerGenerate replacerArchive
after_success:
  - cd ../.. && ./gradlew coveralls
